version: '3.8'

services:
  # Next.js Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: foodsnap-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foodsnap
      - REDIS_URL=redis://cache:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
      - cache
    volumes:
      - .env.local:/app/.env.local
      - ./uploads:/app/public/uploads
    networks:
      - foodsnap-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: foodsnap-db
    environment:
      - POSTGRES_DB=foodsnap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foodsnap-network

  # Redis Cache
  cache:
    image: redis:7-alpine
    container_name: foodsnap-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - foodsnap-network

  # Database Migrations
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: foodsnap-migrate
    command: npx prisma migrate deploy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foodsnap
    depends_on:
      - db
    networks:
      - foodsnap-network

volumes:
  postgres-data:
  redis-data:  redis-data:

  uploads:

networks:
  foodsnap-network:
    driver: bridge 